version: "3"

services:
  sql:
    build: ./sql
    volumes:
      - misquote-cohort-27:/var/lib/mysql
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
volumes:
  misquote-cohort-27:
